name: Add Label to Gillian's Issues

on:
  issues:
    types:
      - opened

jobs:
  add_label:
    runs-on: ubuntu-latest

    steps:
    - name: Check GitHub Token
      run: echo ${{ secrets.WORKFLOW_ACCESS }}


      - name: Check if issue creator is Gillian
        id: check_gillian
        run: |
          ISSUE_CREATOR=$(curl -s -H "Authorization: token ${{ secrets.WORKFLOW_ACCESS }}" \
            -X GET "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}" | \
            jq -r '.user.login')
          echo "IS_GILLIAN=$(echo $ISSUE_CREATOR | grep -q 'gillian-meilisearch'; echo $?) >> $GITHUB_ENV"
        shell: bash

      - name: Add label if created by Gillian
        if: env.IS_GILLIAN == '0'
        run: |
          echo "Adding 'gillian' label to the issue"
          curl -s -H "Authorization: token ${{ secrets.WORKFLOW_ACCESS }}" \
            -X POST "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels" \
            -d '["gillian"]'
        shell: bash
