name: Get card info

on:
  issues:
    types: [opened]

jobs:
  updateIssueStatus:
    runs-on: ubuntu-latest
    steps:
      - name: Install axios
        run: npm install axios
      - name: Get issue info
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const axios = require('axios');

            // Set up authentication headers
            const headers = {
               Authorization: 'Bearer ${{ secrets.GITHUB_TOKEN }}',
              'Accept': 'application/vnd.github.inertia-preview+json'
            };

            // Define the issue and project card IDs
            //const issueId = context.payload.issue.id;
            const cardId = context.payload.issue.project_card.id;

            console.log('payload', context.payload);
         


            // Update the project card for the issue
            //axios.get(`https://api.github.com/projects/columns/cards/${cardId}`,{
              //headers
            //}).then(response => {
              //console.log(response.data)
              //console.log('Project card info obtained');
            //}).catch(error => {
              //console.error('Error updating project card:', error);
            //});